---
# Simply setup the various hosts
- hosts: all
  user: root
  roles:
    - role: common

# Install nginx
- hosts: web
  user: root
  roles: 
    - role: nginx
      nginx_sites:
        default:
            - listen 8080
            - server_name _
            - root "/var/www/site"
            - index index.html

  tasks:
    - name: Prepare html folder
      file:
        name=/var/www/site
        owner=www-data
        group=www-data
        mode=755
        state=directory
    - name: Copy content to nginx folder
      template:
        src=index.orig.html.j2
        dest=/var/www/site/index.html
        owner=www-data
        group=www-data



# Install haproxy
- hosts: lb
  user: root
  roles:
    - role: haproxy
      haproxy_frontends:
        - name: default
          bind: '*:80'
          default_backend: webserver
      haproxy_backends:
        - name: webserver
          balance: roundrobin
          servers:
          - name: web1
            ip: "{{ hostvars['web1']['ansible_eth0']['ipv4']['address'] }}"
            port: 8080
          - name: web2
            ip: "{{ hostvars['web2']['ansible_eth0']['ipv4']['address'] }}"
            port: 8080

