---
# Simply setup the various hosts
- hosts: all
  user: root
  roles:
    - role: common

# Install nginx
- hosts: web
  user: root
  roles: 
    - role: nginx
      nginx_sites:
        default:
            - listen 80
            - server_name _
            - root "/var/www/site"
            - index index.html
  tasks:
    - name: Copy content to nginx folder
      templates:
        src=index.orig.html.j2
        dest=/var/www/site/index.html
        state=present


# Install haproxy
- hosts: lb
  user: root
  roles:
    - role: haproxy
      haproxy_frontends:
        - name: default
          bind: '*:80'
          default_backend: 
      haproxy_backends:
        - name: ams-private
          port: 3001
          iface: eth1

