---
# Simply setup the various hosts
- hosts: all
  user: root
  roles:
    - role: common

# Install nginx
- hosts: web
  user: root
  roles: 
    - role: nginx
      nginx_sites:
        default:
            - listen 8080
            - server_name _
            - root "/var/www/site"
            - index index.html

  tasks:
    - name: Copy content to nginx folder
      template:
        src=index.orig.html.j2
        dest=/var/www/site/index.html
        state=present


# Install haproxy
- hosts: lb
  user: root
  roles:
    - role: haproxy
      haproxy_frontends:
        - name: default
          bind: '*:80'
          default_backend: 
      haproxy_backends:
        - name: webserver
          servers:
          - name: web1
            ip: host_vars['web1']['ansible_eth0']['ipv4']['address']
            port: 8080
          - name: web2
            ip: host_vars['web2']['ansible_eth0']['ipv4']['address']
            port: 8080

